### ISSUE TITLE
odmitam elaborovat

### ISSUE THREAD

**Issue by andrewzn69** [Lena-hal/TdA24-IdealneNazevTymu#1]
![flkdsjflks](https://i.pinimg.com/originals/90/f7/f9/90f7f99633b4e788252e508c88112295.jpg)

**Comment by a-dam-s** [comment]
kys![Screenshot_2023-11-07-21-59-23-81_3aea4af51f236e4932235fdada7d1643.jpg](https://github.com/Lena-hal/TdA24-IdealneNazevTymu/assets/75887447/ad6b8034-b6fd-45dd-b039-da74565114c0)
